name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ⬇️ fabrique le nom d'image en minuscules
      - name: Compute lowercase image name
        id: img
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .           # adapte si ton Dockerfile n'est pas à la racine
          file: ./Dockerfile   # idem
          push: true
          tags: |
            ${{ steps.img.outputs.IMAGE }}:${{ github.sha }}
            ${{ steps.img.outputs.IMAGE }}:latest
