name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Private Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image name
        id: repo
        run: echo "repo=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ steps.repo.outputs.repo }}:${{ github.sha }}
            ${{ steps.repo.outputs.repo }}:latest

